language: r
sudo: false

r_github_packages: 
  - jimhester/covr

env:
  global:
    - NOT_CRAN=true
    - secure: "nhzZdgVEOmRO/pCpkb6vBgTbLU2igXmb5gbX+QWaV5YzDT5pqMnT+AtE5/+GMH7QxfFE1SKeA/r2w8XomNMpDvhIIpedwHpGywRGK3rtav2u108oQ73m2k2D3AQZ/YTAx7xPgVwCMveUqZ3xDyGkt220J3Hwfkpe341B2xQH0JQ="

notifications:
  slack: talkstats:AdIullnahcEy4dX12JYbD4G9
  email:
    on_success:      change
    on_failure:      change

    
after_success:
  - Rscript -e 'covr::coveralls()'
  
r_build_args: "--resave-data=best"
r_check_args: "--as-cran"

r:
    - oldrel
    #- release
    - devel
os:
    - linux
    - osx

matrix:
    fast_finish: true
    allow_failures:
    #-   r: oldrel
    #    os: osx
    -   r: release
        os: osx
    -   r: devel
        os: osx 


